# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FreeMED-Relay
version:      0.2.2
version_from: lib/FreeMED/Relay.pm
installdirs:  site
requires:
    JSON:                          1.00
    LWP::UserAgent:                2.033
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
